// Database adapter - Firebase with localStorage fallback
// All exports are async to support both Firebase and localStorage
export {
  initializeDB,
  getTrips,
  addTrip,
  getPackages,
  addPackage,
  getAgents,
  saveAgents,
  getAgentById,
  getAgentByUsername,
  addAgent,
  getBookings,
  saveBookings,
  addBooking,
  updateBookingStatus,
  getPromoCodes,
  savePromoCodes,
  addPromoCode,
  deletePromoCode,
  validatePromoCode,
  consumePromoCode,
  getReviews,
  addReview,
  getSocialMedia,
  saveSocialMedia,
  getSettings,
  saveSettings,
} from './db.adapter';
